name: MLflow CI

on:
  push:
    branches:
      - main   # jalankan CI/CD tiap push ke branch main
  pull_request:
    branches:
      - main

jobs:
  train-and-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
         python-version: 3.11       # sesuaikan dengan python di conda.yaml
         environment-file: conda.yaml
         auto-activate-base: false

      - name: Activate environment and run MLflow
        run: |
          conda activate credit-scoring-env
          mlflow run . -P n_estimators=300 -P max_depth=25 -P dataset="train_pca.csv"

