name: MLflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12       # Sesuaikan dengan conda.yaml
          environment-file: conda.yaml
          auto-activate-base: false
      - name: Run MLflow project
        run: |
         conda run -n credit-scoring-env --no-capture-output mlflow run . -P n_estimators=300 -P max_depth=25 -P dataset="train_pca.csv"

